---
sudo: false
language: ruby
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 2.1
  - 2.2
env:
  - PUPPET_GEM_VERSION="~> 4.5.0"
  - PUPPET_GEM_VERSION="~> 4.6.0"
  - PUPPET_GEM_VERSION="~> 4.7.0"
  - PUPPET_GEM_VERSION="~> 4.8.0"
