# This file is generated by ModuleSync, do not edit!
require 'puppetlabs_spec_helper/module_spec_helper'
require 'rspec-puppet-facts'

# Put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError # rubocop:disable Lint/HandleExceptions
end

include RspecPuppetFacts

RSpec.configure do |config|
  config.mock_with :rspec

  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  config.after(:suite) do
    RSpec::Puppet::Coverage.report!(100)
  end
end
